server:
    port: 8080
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: ApiGateWayForService
 cloud:
    gateway:
      routes:
      - id: WorldExplorerCaseStudy
        uri: http://localhost:8081/
        predicates:
        - Path=/api/v1/**
      - id: WorldExplorerCaseStudyForUser
        uri: http://localhost:8084/
        predicates:
        - Path=/api/v1/**
      - id: WorldExplorerApp_JWTService
        uri: http://localhost:8082/
        predicates:
        - Path=/api/jwt/**
          
      
  